site_name: DeepMCPAgent
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
nav:
  - Home: docs/index.md
  - Installation: docs/installation.md
  - Getting Started: docs/getting-started.md
  - Server Specs & Auth: docs/server-specs.md
  - Model Setup: docs/model-setup.md
  - CLI: docs/cli.md
  - Examples: docs/examples.md
  - API: docs/api.md
  - Troubleshooting: docs/troubleshooting.md
  - FAQ: docs/faq.md
  - Changelog: docs/changelog.md
